INSERT INTO CATEGORIE VALUES (1,'Chemises');
INSERT INTO CATEGORIE VALUES (2,'Pantalons');
INSERT INTO CATEGORIE VALUES (3,'Vestes');

INSERT INTO TAILLE VALUES (1,'S');
INSERT INTO TAILLE VALUES (2,'M');
INSERT INTO TAILLE VALUES (3,'L');
INSERT INTO TAILLE VALUES (4,'XL');


INSERT INTO CLIENT VALUES (1,'Ben Salah','Ahmed','ahmed.bensalah@gmail.com','1234','98123456');

INSERT INTO CLIENT VALUES (2,'Trabelsi','Yasmine','yasmine.trabelsi@yahoo.fr','1234','22134567');

INSERT INTO CLIENT VALUES (3,'Gharbi','Mehdi','mehdi.gharbi@outlook.com','1234','55781234');

INSERT INTO PRODUIT VALUES
(1,'Chemise Byrsa Classique',
 'Chemise élégante homme',
 120,
 15,
 'lien-image',
 1);

INSERT INTO PRODUIT VALUES
(2,'Pantalon Atlas',
 'Pantalon moderne',
 180,
 10,
 'lien-image',
 2);

INSERT INTO PRODUIT VALUES
(3,'Veste Numide',
 'Veste premium',
 350,
 7,
 'lien-image',
 3);
 
INSERT INTO PRODUIT_TAILLE VALUES (1,1);
INSERT INTO PRODUIT_TAILLE VALUES (1,2);
INSERT INTO PRODUIT_TAILLE VALUES (1,3);

INSERT INTO PRODUIT_TAILLE VALUES (2,2);
INSERT INTO PRODUIT_TAILLE VALUES (2,3);

INSERT INTO PRODUIT_TAILLE VALUES (3,3);
INSERT INTO PRODUIT_TAILLE VALUES (3,4);

INSERT INTO COMMANDE VALUES
(1,SYSDATE,'En préparation',1);

INSERT INTO COMMANDE VALUES
(2,SYSDATE,'Expédiée',2);

INSERT INTO LIGNE_COMMANDE VALUES
(1,1,2,120);

INSERT INTO LIGNE_COMMANDE VALUES
(1,2,1,180);

INSERT INTO LIGNE_COMMANDE VALUES
(2,3,1,350);

INSERT INTO PAIEMENT VALUES
(1,'Carte bancaire',420,SYSDATE,1);

INSERT INTO PAIEMENT VALUES
(2,'Paiement livraison',350,SYSDATE,2);

INSERT INTO LIVRAISON VALUES
(1,'Rue Habib Bourguiba','Tunis','En préparation',1);

INSERT INTO LIVRAISON VALUES
(2,'Ariana centre','Ariana','Livrée',2);

commit;